### ISSUE TITLE
Status of this module

### ISSUE THREAD

**Issue by RomkeVdMeulen** [aurelia/cache#2]
I'm looking for some kind of cache abstraction for my project and found this. I can see it's quite young and there's a little code here, but I don't know much else about it. Could you give me a rough idea of the status of this project and whether you'd advise using it in production right now?

**Comment by EisenbergEffect** [comment]
This is the place to find it. However, this module isn't ready for use yet. It's missing lots of implementation details.

**Comment by AStoker** [comment]
We're going to be looking into cache options soon, and am intrigued by this. Are there plans for the development of this? If not urgent plans, is there a direction that should be taken for anybody interested in doing a PR to help with this?

**Comment by EisenbergEffect** [comment]
There are plans for development, but it has taken a back seat since it isn't as high a priority for us as other modules. We would love to see a pull request to expand this out.

The idea for the implementation came from this: https://github.com/jmdobry/angular-cache  We wanted to modernize that for ES 2015, removing as many framework specific things as possible and just have a nice, pure JS basic cache mechanism. Another idea was to make it compatible with the Cache spec associated with Fetch. We hadn't fleshed all this out yet, so we would love some community contributions on this for sure.

Let me know what you think.

**Comment by AStoker** [comment]
That angular cache implementation is kinda slick. I had started something similar to that a while back, but made the mistake of using indexedDB which isn't fully supported :P I might take a crack at this. I'm with you in thinking that this won't need many framework specific features. If you bring it down to bare bones features, I see no reason we'd need any additional framework. When you start getting into Fetch, you might want to make sure you have a polyfill in place. 
I'll try and tackle some of this after I get infinite scrolling and horizontal scrolling working in the virtual-repeat repo, since we need those features in our product before caching.

**Comment by EisenbergEffect** [comment]
Sounds great. All the contributions you mention would be most welcome. Thanks!

**Comment by RomkeVdMeulen** [comment]
Since I needed some basic caching in my application and couldn't wait on this, I've already created a [simple implementation](https://gist.github.com/RomkeVdMeulen/d0ede5acab30a11ed418f3c7f64a95db) inspired by this repo. Perhaps it can serve as inspiration for the next guy. Example usage:

```ts
import {autoinject} from "aurelia-framework";
import {Cache, CacheService, CACHE_STORE} from "./cache";

@autoinject
export class MyCacheComponent {

	private cache: Cache;
	private myItems: any[];

	constructor(cacheService: CacheService) {
		this.cache = cacheService
			.configure("MyCacheComponent", { store: CACHE_STORE.PERSISTENT })
			.getCache("MyCacheComponent");

		let myItems: any[] = this.cache.getItem("my-items");
		if (myItems !== null) {
			this.myItems = myItems;
		}
	}

	addItem(item: any) {
		this.myItems.push(item);
		this.cache.setItem("my-items", this.myItems);
	}
}
```

**Comment by swalters** [comment]
I think this needs some attention.  Devs coming from Angular1 will expect a simple cache implementation.

**Comment by EisenbergEffect** [comment]
Are you volunteering? ;)

**Comment by AStoker** [comment]
I've been heads down for the past few months, so I haven't had time to commit to this yet. But if there's somebody else willing to help out, that would be awesome.

**Comment by swalters** [comment]
I'm using @RomkeVdMeulen's solution and it works well for me.  How much more is needed out of a caching solution?
